### ISSUE TITLE
XXX can't be opened using the built-in administrator account

### ISSUE THREAD

**Issue by derwasp** [gusztavvargadr/vagrant#37]
If I try to use either Edge or Photos application, the following pop-up appears.

![image](https://cloud.githubusercontent.com/assets/10754345/20963296/277150b4-bc6d-11e6-84f4-a53a4f5c1eb8.png)

Is this expected?

**Comment by gusztavvargadr** [comment]
@derwasp thanks for reporting the issue. This is due to that UAC is disabled, which is a requirement by Vagrant for being able to run provisioners. I'll check if I can find a fix, you can try this workaround in the meantime:

http://www.virtualizationhowto.com/2015/07/windows-10-edge-opened-builtin-administrator-account/

**Comment by derwasp** [comment]
@gusztavvargadr thank you. Well, it's not a blocker for me, I just thought it's good to have it tracked here.

**Comment by gusztavvargadr** [comment]
Obsolete with #39 in favor of https://github.com/gusztavvargadr/workstations/issues/3.
